### ISSUE TITLE
what's nodo v can work???8.?.?

### ISSUE THREAD

**Issue by mangopool** [NixPlatform/node-open-mining-portal#1]
Error: The module '/home/pool/nomp/node_modules/multi-hashing/build/Release/multihashing.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/home/pool/nomp/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/pool/nomp/node_modules/multi-hashing/index.js:1:99)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

**Comment by phamels** [comment]
Node 8.x.x or higher as the requirements say
